// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpartaIMSEng24.Data;

namespace SpartaIMSEng24.Migrations
{
    [DbContext(typeof(SpartaIMSContext))]
    [Migration("20190326125451_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpartaIMSEng24.Models.Cohort", b =>
                {
                    b.Property<int>("CohortID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CohortName");

                    b.Property<int>("CohortNumber");

                    b.Property<int?>("SpecialisationSpecID");

                    b.HasKey("CohortID");

                    b.HasIndex("SpecialisationSpecID");

                    b.ToTable("Cohorts");
                });

            modelBuilder.Entity("SpartaIMSEng24.Models.JobRole", b =>
                {
                    b.Property<int>("JobRoleID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("JobRoleName");

                    b.HasKey("JobRoleID");

                    b.ToTable("JobRoles");
                });

            modelBuilder.Entity("SpartaIMSEng24.Models.SpartanUser", b =>
                {
                    b.Property<int>("SpartanID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CohortID");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("FullName");

                    b.Property<int>("JobRoleID");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password");

                    b.HasKey("SpartanID");

                    b.HasIndex("CohortID");

                    b.HasIndex("JobRoleID");

                    b.ToTable("SpartanUsers");
                });

            modelBuilder.Entity("SpartaIMSEng24.Models.Specialisation", b =>
                {
                    b.Property<int>("SpecID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SpecName");

                    b.HasKey("SpecID");

                    b.ToTable("Specialisations");
                });

            modelBuilder.Entity("SpartaIMSEng24.Models.Cohort", b =>
                {
                    b.HasOne("SpartaIMSEng24.Models.Specialisation")
                        .WithMany("Cohorts")
                        .HasForeignKey("SpecialisationSpecID");
                });

            modelBuilder.Entity("SpartaIMSEng24.Models.SpartanUser", b =>
                {
                    b.HasOne("SpartaIMSEng24.Models.Cohort", "Cohort")
                        .WithMany("SpartanUsers")
                        .HasForeignKey("CohortID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SpartaIMSEng24.Models.JobRole", "JobRole")
                        .WithMany("SpartanUsers")
                        .HasForeignKey("JobRoleID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
